### ISSUE TITLE
Feature request : stream only a certain window + allow bottom screen to stream separate window

### ISSUE THREAD

**Issue by Golem642** [zoeyjodon/moonlight-N3DS#25]
Hello, it would be nice to be able to only stream one window instead of the whole screen, i believe it could potentially speed up the streaming.
Even if it doesn't, adding an option to stream a separate window onto the bottom screen would be nice.
For example : i have my Cemu setup where i can popup the gamepad screen in a separate window. So streaming the main screen on the top window and the gamepad screen on the bottom window would be really cool
I hope it's possible to do this, thanks

**Comment by zoeyjodon** [comment]
I'm not sure about streaming a single window, since that would need to be a feature created on both the moonlight and the sunshine side of things. Personally, I think implementing dual screen streaming would be easier given Sunshine's current setup: https://github.com/zoeyjodon/moonlight-N3DS/issues/20. 

Both cases will require new features in sunshine, but dual monitor streaming would be lower effort since we wouldn't need to add logic narrowing the stream to a single window in addition to adding a second video stream.
